
guard 'rspec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})             { |m| "spec/#{m[1]}_spec.rb" }
end

notification :libnotify,
             :timeout => 1,
             :transient => true,
             :append => true