-module(problem_2).

-compile(export_all).

%~ Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

%~ 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%~ Find the sum of all the even-valued terms in the sequence which do not exceed four million.


sum(Max) -> sum(Max, 1, 2, []).
sum(Max, _Lower, Higher, List) when Higher >= Max -> lists:sum(List);
sum(Max, Lower, Higher, List) -> 
  case (Higher rem 2) of
    1 -> sum(Max, Higher, Lower + Higher, List);
    0 -> sum(Max, Higher, Lower + Higher, [Higher | List])
  end.